# review-epubmaker向けの設定ファイルの例。
# yamlファイルをReVIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: dbtimes-vol01
# 書名
booktitle: The Database Times vol.1
# 著者
aut: はやみず，hogelog，suu-g，yuyarin
cir: Hotchpotch Society
edt: はやみず
date: 2012-8-18

# 以下はオプション
# prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
coverfile: _cover.html
# coverimage: 表紙用画像ファイル
coverimage: cover.png
# 固有IDに使用するドメイン
urnid: http://hayamiz.com/~hotchpotch/books/dbtimes-vol01/1.0.1/
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること
stylesheet: dbtimes.css
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 3
# review-compileに渡すパラメータ
params: --stylesheet=dbtimes.css
# 目次生成用？
mytoc: true
# 奥付生成用
colophon: _colophon.html
texstyle:
pubhistory: |
  2012年12月16日 v1.0.1版発行
debug: true
